#!/usr/bin/env python3
"""
anetbbs-scaffold-door — generate a starter `builtin_python` door.

Writes a minimal, working door module (write/read_line, nothing else)
to `anetbbs/features/<slug>.py`, and creates a matching `Game` row so
it shows up at `/admin/games/` ready to review and activate — never
live/`is_active` on its own, so running this script can't put an
unfinished door in front of a real player by accident.

See "Writing a builtin_python door" in docs/17-development.md for the
full session API contract (write()/read_line()/user — that's the
entire surface a door can rely on) and why it's kept that narrow.

Usage:
    python tools/scaffold_builtin_door.py mydoor "My Door"
    python tools/scaffold_builtin_door.py mydoor "My Door" \\
        --category adventure --description "A quick text adventure."

DATABASE_URL is read from the environment, same convention as every
other tools/*.py script and the BBS itself.

Exit codes: 0 = success, 1 = fatal error.
"""
import argparse
import os
import re
import sys
from pathlib import Path

_TTY = sys.stdout.isatty()

def _c(code: str, text: str) -> str:
    return f'\x1b[{code}m{text}\x1b[0m' if _TTY else text

def ok(s):   print(_c('92', f'  ✓ {s}'))
def err(s):  print(_c('91', f'  ✗ {s}'), file=sys.stderr)
def info(s): print(_c('90', f'    {s}'))
def head(s): print(_c('96;1', f'\n{s}'))


_SLUG_RE = re.compile(r'^[a-z][a-z0-9_]{1,49}$')

_TEMPLATE = '''"""{title} — a builtin_python ANetBBS door.

Generated by tools/scaffold_builtin_door.py. See "Writing a
builtin_python door" in docs/17-development.md for the full session
API contract this relies on (write()/read_line()/user, nothing else).
"""


async def launch_{func_slug}(session, username: str):
    await session.write('\\r\\n{title}\\r\\n\\r\\n')
    await session.write(f'Hello, {{username}}!\\r\\n')
    name = await session.read_line('What should I call your character? ')
    name = name.strip() or username
    await session.write(f'\\r\\nWelcome, {{name}}.\\r\\n')
    await session.write('(This is the whole door -- add more turns here.)\\r\\n')
    await session.read_line('\\r\\nPress Enter to return to the menu...')
'''


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog='anetbbs-scaffold-door',
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument('slug', help='Short, lowercase, unique game slug '
                                '(letters/digits/underscore, e.g. "mydoor")')
    p.add_argument('title', help='Display name shown in the game catalog')
    p.add_argument('--category', default='other',
                   help='Game Center category (default: other)')
    p.add_argument('--description', default='',
                   help='One-line description for the catalog listing')
    p.add_argument('--min-access-level', type=int, default=0,
                   help='Minimum access level required to play (default: 0)')
    p.add_argument('--force', action='store_true',
                   help='Overwrite the door file if it already exists')
    return p


def _get_db_uri() -> str:
    uri = os.environ.get('DATABASE_URL')
    if uri:
        return uri
    try:
        from anetbbs.config import get_config
        cfg = get_config(os.environ.get('FLASK_ENV', 'production'))
        return cfg.SQLALCHEMY_DATABASE_URI
    except Exception:
        return 'sqlite:///data/anetbbs.db'


def main():
    parser = build_parser()
    args = parser.parse_args()

    if not _SLUG_RE.match(args.slug):
        err(f'Invalid slug {args.slug!r} — lowercase letters/digits/'
            f'underscore only, starting with a letter, 2-50 chars.')
        return 1

    head(f'Scaffolding builtin_python door "{args.title}" ({args.slug})')

    repo_root = Path(__file__).resolve().parent.parent
    module_path = repo_root / 'anetbbs' / 'features' / f'{args.slug}.py'
    func_slug = args.slug.replace('-', '_')

    if module_path.exists() and not args.force:
        err(f'{module_path} already exists — pass --force to overwrite.')
        return 1

    module_path.write_text(
        _TEMPLATE.format(title=args.title, func_slug=func_slug))
    ok(f'Wrote {module_path.relative_to(repo_root)}')

    from anetbbs.web_app import create_app
    from anetbbs.models import db, Game

    app = create_app()
    with app.app_context():
        if Game.query.filter_by(slug=args.slug).first():
            err(f'A Game row with slug {args.slug!r} already exists — '
                f'edit it directly at /admin/games/ instead.')
            return 1
        game = Game(
            name=args.title,
            slug=args.slug,
            description=args.description or f'{args.title} — a builtin_python door.',
            category=args.category,
            game_type='builtin_python',
            web_game_module=f'anetbbs.features.{args.slug}:launch_{func_slug}',
            min_access_level=args.min_access_level,
            is_active=False,
        )
        db.session.add(game)
        db.session.commit()
        ok(f'Created draft Game row (id={game.id}, is_active=False)')

    info('')
    info('Next steps:')
    info(f'  1. Edit {module_path.relative_to(repo_root)} — replace the')
    info('     placeholder turns with your actual door logic.')
    info('  2. Review the draft at /admin/games/ and check "Active" once')
    info('     it plays the way you want — it stays hidden from players')
    info('     until then.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
